import { Gameweek, Player } from "~/features/AppData/appDataTypes";
import { ElementStatus } from "~/features/AppData/fplTypes";

export const player: Player = {
  id: 302,
  first_name: "Bruno",
  second_name: "Fernandes",
  web_name: "Fernandes",
  news: "Too good",
  status: ElementStatus.INJURED,
  now_cost: 115,
  photo: "141746.jpg",
  cost_change_start: 5,
  chance_of_playing_next_round: null,
  chance_of_playing_this_round: null,
  total_points: 228,
  selected_by_percent: "50.4",
  transfers_in_event: 2524,
  transfers_out_event: 31638,
  element_type: {
    singular_name_short: "MID",
  },
  team: {
    id: 13,
    short_name: "MUN",
  },
  linked_data: {
    understat_id: "1228",
    past_matches: [
      {
        opponent_short_title: "LEE",
        is_home: false,
        match_time: 90,
        match_g: 0,
        match_a: 0,
        match_shots: 5,
        match_key_passes: 2,
        match_xg: 0.42672669887542725,
        match_xa: 0.12024029344320297,
        match_xga: 0.216834,
      },
      {
        opponent_short_title: "AVL",
        is_home: false,
        match_time: 87,
        match_g: 1,
        match_a: 0,
        match_shots: 4,
        match_key_passes: 3,
        match_xg: 1.0192543268203735,
        match_xa: 0.048688460141420364,
        match_xga: 0.565472,
      },
      {
        opponent_short_title: "LEI",
        is_home: true,
        match_time: 11,
        match_g: 0,
        match_a: 0,
        match_shots: 1,
        match_key_passes: 0,
        match_xg: 0.06144723668694496,
        match_xa: 0,
        match_xga: 0.991522,
      },
      {
        opponent_short_title: "LIV",
        is_home: true,
        match_time: 90,
        match_g: 1,
        match_a: 0,
        match_shots: 6,
        match_key_passes: 2,
        match_xg: 0.36556729674339294,
        match_xa: 0.47926193475723267,
        match_xga: 2.938,
      },
      {
        opponent_short_title: null,
        is_home: true,
        match_time: 90,
        match_g: 0,
        match_a: 1,
        match_shots: 6,
        match_key_passes: 1,
        match_xg: 0.2636248767375946,
        match_xa: 0.014647945761680603,
        match_xga: 0.872643,
      },
    ],
    season_time: 3117,
    season_game: 37,
    season_g: 18,
    season_a: 12,
    season_shots: 121,
    season_key_passes: 95,
    season_xg: 16.0194544615224,
    season_xa: 11.474995978176594,
    season_xga: 41.917999,
    teamcolorcodes: {
      team: "Man Utd",
      background: "#dc1f29",
      text: "#fae935",
      highlight: "#000",
    },
    transfers_delta_event: 0,
    previous_gameweeks: [],
    next_gameweeks: [
      {
        opponent_team_short_name: "LEE",
        is_home: true,
        event: 1,
        finished: false,
        difficulty: 3,
      },
      {
        opponent_team_short_name: "SOU",
        is_home: false,
        event: 2,
        finished: false,
        difficulty: 2,
      },
      {
        opponent_team_short_name: "WOL",
        is_home: false,
        event: 3,
        finished: false,
        difficulty: 3,
      },
      {
        opponent_team_short_name: "NEW",
        is_home: true,
        event: 4,
        finished: false,
        difficulty: 2,
      },
      {
        opponent_team_short_name: "WHU",
        is_home: false,
        event: 5,
        finished: false,
        difficulty: 4,
      },
      {
        opponent_team_short_name: "AVL",
        is_home: true,
        event: 6,
        finished: false,
        difficulty: 2,
      },
      {
        opponent_team_short_name: "EVE",
        is_home: true,
        event: 7,
        finished: false,
        difficulty: 4,
      },
      {
        opponent_team_short_name: "LEI",
        is_home: false,
        event: 8,
        finished: false,
        difficulty: 3,
      },
      {
        opponent_team_short_name: "LIV",
        is_home: true,
        event: 9,
        finished: false,
        difficulty: 4,
      },
      {
        opponent_team_short_name: "TOT",
        is_home: false,
        event: 10,
        finished: false,
        difficulty: 4,
      },
      {
        opponent_team_short_name: "MCI",
        is_home: true,
        event: 11,
        finished: false,
        difficulty: 4,
      },
      {
        opponent_team_short_name: "WAT",
        is_home: false,
        event: 12,
        finished: false,
        difficulty: 2,
      },
      {
        opponent_team_short_name: "CHE",
        is_home: false,
        event: 13,
        finished: false,
        difficulty: 4,
      },
      {
        opponent_team_short_name: "ARS",
        is_home: true,
        event: 14,
        finished: false,
        difficulty: 3,
      },
      {
        opponent_team_short_name: "CRY",
        is_home: true,
        event: 15,
        finished: false,
        difficulty: 2,
      },
      {
        opponent_team_short_name: "NOR",
        is_home: false,
        event: 16,
        finished: false,
        difficulty: 2,
      },
      {
        opponent_team_short_name: "BRE",
        is_home: false,
        event: 17,
        finished: false,
        difficulty: 2,
      },
      {
        opponent_team_short_name: "BHA",
        is_home: true,
        event: 18,
        finished: false,
        difficulty: 2,
      },
      {
        opponent_team_short_name: "NEW",
        is_home: false,
        event: 19,
        finished: false,
        difficulty: 2,
      },
      {
        opponent_team_short_name: "BUR",
        is_home: true,
        event: 20,
        finished: false,
        difficulty: 2,
      },
      {
        opponent_team_short_name: "WOL",
        is_home: true,
        event: 21,
        finished: false,
        difficulty: 2,
      },
      {
        opponent_team_short_name: "AVL",
        is_home: false,
        event: 22,
        finished: false,
        difficulty: 3,
      },
      {
        opponent_team_short_name: "WHU",
        is_home: true,
        event: 23,
        finished: false,
        difficulty: 3,
      },
      {
        opponent_team_short_name: "BUR",
        is_home: false,
        event: 24,
        finished: false,
        difficulty: 2,
      },
      {
        opponent_team_short_name: "SOU",
        is_home: true,
        event: 25,
        finished: false,
        difficulty: 2,
      },
      {
        opponent_team_short_name: "LEE",
        is_home: false,
        event: 26,
        finished: false,
        difficulty: 3,
      },
      {
        opponent_team_short_name: "WAT",
        is_home: true,
        event: 27,
        finished: false,
        difficulty: 2,
      },
      {
        opponent_team_short_name: "MCI",
        is_home: false,
        event: 28,
        finished: false,
        difficulty: 5,
      },
      {
        opponent_team_short_name: "TOT",
        is_home: true,
        event: 29,
        finished: false,
        difficulty: 3,
      },
      {
        opponent_team_short_name: "LIV",
        is_home: false,
        event: 30,
        finished: false,
        difficulty: 4,
      },
      {
        opponent_team_short_name: "LEI",
        is_home: true,
        event: 31,
        finished: false,
        difficulty: 4,
      },
      {
        opponent_team_short_name: "EVE",
        is_home: false,
        event: 32,
        finished: false,
        difficulty: 3,
      },
      {
        opponent_team_short_name: "NOR",
        is_home: true,
        event: 33,
        finished: false,
        difficulty: 2,
      },
      {
        opponent_team_short_name: "ARS",
        is_home: false,
        event: 34,
        finished: false,
        difficulty: 4,
      },
      {
        opponent_team_short_name: "BRE",
        is_home: true,
        event: 35,
        finished: false,
        difficulty: 2,
      },
      {
        opponent_team_short_name: "BHA",
        is_home: false,
        event: 36,
        finished: false,
        difficulty: 3,
      },
      {
        opponent_team_short_name: "CHE",
        is_home: true,
        event: 37,
        finished: false,
        difficulty: 4,
      },
      {
        opponent_team_short_name: "CRY",
        is_home: false,
        event: 38,
        finished: false,
        difficulty: 2,
      },
    ],
  },
};

export const gameweeks: Gameweek[] = [
  {
    id: 34,
    deadline_time: "2021-05-23T13:30:00Z",
    is_previous: false,
    is_current: true,
    is_next: false,
  },
  {
    id: 35,
    deadline_time: "2021-05-23T13:30:00Z",
    is_previous: false,
    is_current: false,
    is_next: true,
  },
  {
    id: 36,
    deadline_time: "2021-05-23T13:30:00Z",
    is_previous: false,
    is_current: false,
    is_next: false,
  },
  {
    id: 37,
    deadline_time: "2021-05-23T13:30:00Z",
    is_previous: false,
    is_current: false,
    is_next: false,
  },
  {
    id: 38,
    deadline_time: "2021-05-23T13:30:00Z",
    is_previous: false,
    is_current: false,
    is_next: false,
  },
];
