import { ClientPlayer } from "@open-fpl/app/features/PlayerData/playerDataTypes";
import { FullChangePlayer } from "@open-fpl/app/features/TeamPlanner/teamPlannerTypes";
import { ElementStatus } from "@open-fpl/data/features/RemoteData/fplTypes";

export const player: ClientPlayer = {
  id: 302,
  first_name: "Bruno",
  second_name: "Fernandes",
  web_name: "Fernandes",
  news: "Too good",
  status: ElementStatus.INJURED,
  now_cost: 115,
  cost_change_start: 5,
  total_points: 228,
  selected_by_percent: "50.4",
  transfers_in_event: 0,
  transfers_out_event: 0,
  cost_change_event: 0,
  element_type: {
    singular_name_short: "MID",
  },
  team: {
    id: 13,
    short_name: "MUN",
  },
  linked_data: {
    understat_id: "1228",
    past_matches: [
      {
        opponent_id: null,
        opponent_short_title: "LEE",
        is_home: false,
        match_time: 90,
        match_g: 0,
        match_a: 0,
        match_shots: 5,
        match_key_passes: 2,
        match_ga: 0,
        match_xg: 0.42672669887542725,
        match_xa: 0.12024029344320297,
        match_xgi: 0.5469669923186302,
        match_xga: 0.216834,
      },
      {
        opponent_id: null,
        opponent_short_title: "AVL",
        is_home: false,
        match_time: 87,
        match_g: 1,
        match_a: 0,
        match_shots: 4,
        match_key_passes: 3,
        match_ga: 0,
        match_xg: 1.0192543268203735,
        match_xa: 0.048688460141420364,
        match_xgi: 1.067942786961794,
        match_xga: 0.565472,
      },
      {
        opponent_id: null,
        opponent_short_title: "LEI",
        is_home: true,
        match_time: 11,
        match_g: 0,
        match_a: 0,
        match_shots: 1,
        match_key_passes: 0,
        match_ga: 0,
        match_xg: 0.06144723668694496,
        match_xa: 0,
        match_xgi: 0.06144723668694496,
        match_xga: 0.991522,
      },
      {
        opponent_id: null,
        opponent_short_title: "LIV",
        is_home: true,
        match_time: 90,
        match_g: 1,
        match_a: 0,
        match_shots: 6,
        match_key_passes: 2,
        match_ga: 0,
        match_xg: 0.36556729674339294,
        match_xa: 0.47926193475723267,
        match_xgi: 0.8448292315006256,
        match_xga: 2.938,
      },
      {
        opponent_id: null,
        opponent_short_title: null,
        is_home: true,
        match_time: 90,
        match_g: 0,
        match_a: 1,
        match_shots: 6,
        match_key_passes: 1,
        match_ga: 0,
        match_xg: 0.2636248767375946,
        match_xa: 0.014647945761680603,
        match_xgi: 0.2782728224992752,
        match_xga: 0.872643,
      },
    ],
    season_time: 3117,
    season_game: 37,
    season_g: 18,
    season_a: 12,
    season_shots: 121,
    season_key_passes: 95,
    season_ga: 0,
    season_xg: 16.0194544615224,
    season_xa: 11.474995978176594,
    season_xgi: 27.494450439698994,
    season_xga: 41.917999,
    previous_gameweeks: [],
  },
  client_data: {
    starred_index: -1,
    is_custom_player: false,
    gameweeks: [
      [],
      [
        {
          is_home: true,
          event: 1,
          is_finished: false,
          difficulty: 4,
          opponent: {
            name: "Leicester City",
            short_name: "LEI",
            strength_attack_home: 0,
            strength_attack_away: 0,
            strength_defence_home: 0,
            strength_defence_away: 0,
          },
        },
      ],
      [
        {
          is_home: false,
          event: 2,
          is_finished: false,
          difficulty: 2,
          opponent: {
            name: "Southampton",
            short_name: "SOU",
            strength_attack_home: 0,
            strength_attack_away: 0,
            strength_defence_home: 0,
            strength_defence_away: 0,
          },
        },
      ],
      [
        {
          is_home: true,
          event: 3,
          is_finished: false,
          difficulty: 3,
          opponent: {
            name: "Wolverhampton",
            short_name: "WOL",
            strength_attack_home: 0,
            strength_attack_away: 0,
            strength_defence_home: 0,
            strength_defence_away: 0,
          },
        },
      ],
      [
        {
          is_home: true,
          event: 4,
          is_finished: false,
          difficulty: 1,
          opponent: {
            name: "Newcastle United",
            short_name: "NEW",
            strength_attack_home: 0,
            strength_attack_away: 0,
            strength_defence_home: 0,
            strength_defence_away: 0,
          },
        },
      ],
      [
        {
          is_home: false,
          event: 5,
          is_finished: false,
          difficulty: 5,
          opponent: {
            name: "West Ham Uniter",
            short_name: "WHU",
            strength_attack_home: 0,
            strength_attack_away: 0,
            strength_defence_home: 0,
            strength_defence_away: 0,
          },
        },
      ],
    ],
  },
};

export const fullChangePlayer: FullChangePlayer = {
  ...player,
  pick: {
    element: player.id,
    position: 0,
    now_cost: 110,
    selling_price: 110,
    purchase_price: 100,
    multiplier: 1,
    is_captain: false,
    is_vice_captain: false,
  },
};
