import { Fixture } from "@open-fpl/data/features/RemoteData/fplTypes";

const mockData: Fixture[] = [
  {
    code: 0,
    event: 1,
    finished: false,
    finished_provisional: false,
    id: 0,
    kickoff_time: new Date().toJSON(),
    minutes: 1,
    provisional_start_time: false,
    started: true,
    team_a: 1,
    team_a_score: 0,
    team_h: 2,
    team_h_score: 0,
    stats: [
      {
        identifier: "goals_scored",
        h: [{ value: 1, element: 1 }],
        a: [{ value: 1, element: 1 }],
      },
      {
        identifier: "assists",
        h: [{ value: 1, element: 1 }],
        a: [{ value: 1, element: 1 }],
      },
      {
        identifier: "clean_sheets",
        h: [{ value: 1, element: 1 }],
        a: [{ value: 1, element: 1 }],
      },
      {
        identifier: "goals_conceded",
        h: [{ value: 1, element: 1 }],
        a: [{ value: 1, element: 1 }],
      },
      {
        identifier: "own_goals",
        h: [{ value: 1, element: 1 }],
        a: [{ value: 1, element: 1 }],
      },
      {
        identifier: "penalties_saved",
        h: [{ value: 1, element: 1 }],
        a: [{ value: 1, element: 1 }],
      },
      {
        identifier: "penalties_missed",
        h: [{ value: 1, element: 1 }],
        a: [{ value: 1, element: 1 }],
      },
      {
        identifier: "yellow_cards",
        h: [{ value: 1, element: 1 }],
        a: [{ value: 1, element: 1 }],
      },
      {
        identifier: "red_cards",
        h: [{ value: 1, element: 1 }],
        a: [{ value: 1, element: 1 }],
      },
      {
        identifier: "saves",
        h: [{ value: 1, element: 1 }],
        a: [{ value: 1, element: 1 }],
      },
      {
        identifier: "bonus",
        h: [{ value: 1, element: 10 }],
        a: [{ value: 1, element: 62 }],
      },
      {
        identifier: "bps",
        h: [
          { value: 1, element: 10 },
          { value: 5, element: 15 },
          { value: 7, element: 41 },
          { value: 6, element: 100 },
          { value: 1, element: 17 },
          { value: 5, element: 78 },
          { value: 7, element: 45 },
          { value: 6, element: 140 },
        ],
        a: [
          { value: 8, element: 2 },
          { value: 10, element: 62 },
          { value: 11, element: 59 },
          { value: 20, element: 32 },
          { value: 8, element: 102 },
          { value: 10, element: 162 },
          { value: 11, element: 259 },
          { value: 20, element: 332 },
        ],
      },
    ],
    team_h_difficulty: 1,
    team_a_difficulty: 1,
  },
  {
    code: 0,
    event: 1,
    finished: false,
    finished_provisional: false,
    id: 1,
    kickoff_time: new Date().toJSON(),
    minutes: 1,
    provisional_start_time: false,
    started: true,
    team_a: 1,
    team_a_score: 0,
    team_h: 2,
    team_h_score: 0,
    stats: [],
    team_h_difficulty: 1,
    team_a_difficulty: 1,
  },
  {
    code: 0,
    event: 1,
    finished: false,
    finished_provisional: false,
    id: 0,
    kickoff_time: new Date().toJSON(),
    minutes: 1,
    provisional_start_time: false,
    started: false,
    team_a: 1,
    team_a_score: 0,
    team_h: 2,
    team_h_score: 0,
    stats: [],
    team_h_difficulty: 1,
    team_a_difficulty: 1,
  },
  {
    code: 0,
    event: 1,
    finished: false,
    finished_provisional: false,
    id: 1,
    kickoff_time: new Date().toJSON(),
    minutes: 1,
    provisional_start_time: false,
    started: false,
    team_a: 1,
    team_a_score: 0,
    team_h: 2,
    team_h_score: 0,
    stats: [],
    team_h_difficulty: 1,
    team_a_difficulty: 1,
  },
  {
    code: 0,
    event: 1,
    finished: true,
    finished_provisional: false,
    id: 0,
    kickoff_time: new Date().toJSON(),
    minutes: 1,
    provisional_start_time: false,
    started: false,
    team_a: 1,
    team_a_score: 0,
    team_h: 2,
    team_h_score: 0,
    stats: [
      {
        identifier: "goals_scored",
        h: [{ value: 1, element: 1 }],
        a: [{ value: 1, element: 1 }],
      },
      {
        identifier: "assists",
        h: [{ value: 1, element: 1 }],
        a: [{ value: 1, element: 1 }],
      },
      {
        identifier: "clean_sheets",
        h: [{ value: 1, element: 1 }],
        a: [{ value: 1, element: 1 }],
      },
      {
        identifier: "goals_conceded",
        h: [{ value: 1, element: 1 }],
        a: [{ value: 1, element: 1 }],
      },
      {
        identifier: "own_goals",
        h: [{ value: 1, element: 1 }],
        a: [{ value: 1, element: 1 }],
      },
      {
        identifier: "penalties_saved",
        h: [{ value: 1, element: 1 }],
        a: [{ value: 1, element: 1 }],
      },
      {
        identifier: "penalties_missed",
        h: [{ value: 1, element: 1 }],
        a: [{ value: 1, element: 1 }],
      },
      {
        identifier: "yellow_cards",
        h: [{ value: 1, element: 1 }],
        a: [{ value: 1, element: 1 }],
      },
      {
        identifier: "red_cards",
        h: [{ value: 1, element: 1 }],
        a: [{ value: 1, element: 1 }],
      },
      {
        identifier: "saves",
        h: [{ value: 1, element: 1 }],
        a: [{ value: 1, element: 1 }],
      },
      {
        identifier: "bonus",
        h: [{ value: 1, element: 10 }],
        a: [{ value: 1, element: 62 }],
      },
      {
        identifier: "bps",
        h: [
          { value: 1, element: 10 },
          { value: 5, element: 15 },
          { value: 7, element: 41 },
          { value: 6, element: 100 },
          { value: 1, element: 17 },
          { value: 5, element: 78 },
          { value: 7, element: 45 },
          { value: 6, element: 140 },
        ],
        a: [
          { value: 8, element: 2 },
          { value: 10, element: 62 },
          { value: 11, element: 59 },
          { value: 20, element: 32 },
          { value: 8, element: 102 },
          { value: 10, element: 162 },
          { value: 11, element: 259 },
          { value: 20, element: 332 },
        ],
      },
    ],
    team_h_difficulty: 1,
    team_a_difficulty: 1,
  },
  {
    code: 0,
    event: 1,
    finished: true,
    finished_provisional: false,
    id: 1,
    kickoff_time: new Date().toJSON(),
    minutes: 1,
    provisional_start_time: false,
    started: false,
    team_a: 1,
    team_a_score: 0,
    team_h: 2,
    team_h_score: 0,
    stats: [],
    team_h_difficulty: 1,
    team_a_difficulty: 1,
  },
];

export default mockData;
