name: Data
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
    inputs:
      ignoreSnapshots:
        description: "Ignore snapshots"
        required: true
        default: "false"
jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
      - name: Install packages
        run: yarn
        working-directory: packages/data
      - name: Update data
        run: yarn init-data
        working-directory: packages/data
        env:
          SUPABASE_SECRET_KEY: ${{ secrets.SUPABASE_SECRET_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          IGNORE_SNAPSHOTS: ${{ github.event.inputs.ignoreSnapshots }}
      - name: Trigger open-fpl-data redeploy
        uses: satak/webrequest-action@master
        env:
          FIRE_DEPLOY_DATA_HOOK: ${{ secrets.FIRE_DEPLOY_DATA_HOOK }}
        if: ${{ env.FIRE_DEPLOY_DATA_HOOK == 'true' }}
        with:
          url: ${{ secrets.DEPLOY_DATA_HOOK }}
          method: GET
